---
title: "ADEC 7900 Course Project Report"
author: "Team 3: Paul Gaski, Michael Pomer, Mikaela Renaud-Lowther, and Justin Nevins "
date: "2024-12-11"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Introduction

Broadly, the current analysis intends to investigate the relationship between an individual's income and their purchase of liquor. The nature of this potential relationship is of key importance for policymakers who determine the level of different taxes for a specific geographic area. One type of tax in particular, the alcohol excise tax, is especially relevant to this discussion because it is a selective tax placed on the purchase of alcohol. While the alcohol producer pays this tax at the level of the wholesale transaction, the burden of the tax is in practice placed on the consumer, who is forced to pay a higher retail value for the alcohol. Hence, alcohol excise taxes are often implemented in order to disincentivise the purchase and consumption of alcohol. 

With these dynamics in mind, the current analysis will examine the question, *To what extent does an individual's income affect their purchase (and assumed consumption) of alcohol in Iowa?*

The decision-maker in our analysis is a group of local policymakers evaluating the potential efficacy of alcohol excise taxes. The decision-to-be-made is the optimal level(s) and distribution of these excise taxes across the state of Iowa. Setting tax levels can be a delicate art for policymakers, as they must consider various goals, including both business revenue and social outcomes. The decisions of policymakers not only influence Iowa residents, but can also serve as an example (or lesson) for policymakers across the country. 

# 2. Data Summary

The current analysis combines data from two sources, both of which cover three levels of geographic specificity (county level, city level, and zip-code level). The first source is the Iowa Department of Revenue, which provides data on the sales of liquors in Iowa. More specifically, this data captures the total sales in both dollars and liters across various liquor categories in Iowa from 2012 to 2016. The second source is the American Community Survey, which provides demographic and economic data for the state of Iowa. More specifically, this data captures the total population, income, unemployment, education, and race across the state of Iowa from 2012 to 2016. In combination, these two data sets provide data on both income and liquor sales at the county-, city-, and zip-code levels, which will serve as the basis for our analysis. 

SUMMARIZE THE DATA WITH BASIC DESCRIPTIVE STATISTICS AS APPLICABLE

# 3. Data Analytics

# 4. Conclusion 

# 5. Policy Analytics 